### ISSUE TITLE
Add ConfigMap to ENV support

### ISSUE THREAD

**Issue by devholic** [Rainist/galley#7]
ConfigMag, Secret에서 ENV Variable로 변경되는 기능이 추가되면 좋을 것 같습니당~

**Comment by ryuheechul** [comment]
@devholic 무슨 이슈였는지 이제 기억이 안나네요 -0-

**Comment by cardia** [comment]
galley에 하드코딩 된 무언가가 있다거나? 🤔

**Comment by winterjung** [comment]
이미 구현된 기능 아닐까요?

**Comment by ryuheechul** [comment]
아리송송 달송..

**Comment by devholic** [comment]
So I updated description :doge: @ryuheechul

**Comment by ryuheechul** [comment]
I still can't get it. Can you show me an example, please?

**Comment by devholic** [comment]
Current version of galley converts env variables to configmap, secret or env snippet.
I think extract env variables from configmap, secret, env snippet may help developers in some situations.

e.g.) If configmap provided as input,

```yaml
apiVersion: v1
kind: ConfigMap
data:
  doge: pepe
  sunglass: true
metadata:
  name: some-configmap
  namespace: galley
```

extract env variables like below

```
doge=pepe
sunglass=true
```
